- repo: local
  hooks:
  - id: python-lint
    name: python-lint
    entry: flake8
    language: system
    files: \.(py)$
  - id: rst-lint
    name: rst-lint
    entry: doc8
    language: system
    files: \.(rst)$
