language: python
sudo: false
install:
  - make install
before_script:
  - pip freeze
script:
  - tox
jobs:
  include:
    - stage: core
      python: 3.5
      env: TOXENV=py35
    - stage: core
      python: 3.6
      env: TOXENV=py36
