language: python
sudo: false
python:
  - "3.5"
install: "make install"
before_script:
  - pip freeze
jobs:
  include:
    - stage: test
      script: make test
    - stage: lint
      script: make lint
